-- MySQL Script generated by MySQL Workbench
-- 06/08/14 17:50:48
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pellido` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`dnis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`dnis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dnis_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_dnis_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `prueba`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
